print('<< hello world!', flush=True)
print('<< hello world!', flush=True)
print('<< hello world!', flush=True)
print('<< hello world!', flush=True)
print('<< hello world!', flush=True)
print('<< hello world!', flush=True)
