name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      MAC_CERTS: ${{ secrets.MAC_CERTS }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile code
        run: npm run compile

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ env.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ env.APPLE_API_KEY_ID }}.p8

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        continue-on-error: true
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

          # Signing certificates
          mac_certs: ${{ env.MAC_CERTS }}
          mac_certs_password: ${{ env.MAC_CERTS_PASSWORD }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          # MacOS notarization API key
          APPLE_API_KEY_ID: ${{ env.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER: ${{ env.APPLE_API_KEY_ISSUER }}

      - name: Check for notarization error
        if: startsWith(matrix.os, 'macos')
        run: |
          if [ -f "notarization-error.log" ]; then
            cat notarization-error.log
            exit 1
          fi
